theme: minima
title: Firm Networks 
author: Marc-AurÃ¨le Divernois
email: marc-aurele.divernois@epfl.ch
description: > # this means to ignore newlines until "baseurl:"
  Firm networks

# social links
github_username:  marcaureledivernois # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
